/* JS */ gapi.loaded_0(function(_){var window=this;
var ca,fa,ja,ka,ya,za;_.q=function(a){return function(){return _.ba[a].apply(this,arguments)}};_._DumpException=function(a){throw a;};_.ba=[];ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};fa="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global?window.global:this;
ja=function(a,b){if(b){for(var c=fa,d=a.split("."),e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];f=b(e);f!=e&&null!=f&&ca(c,d,{configurable:!0,writable:!0,value:f})}};ka=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
ja("String.prototype.repeat",function(a){return a?a:function(a){var b=ka(this,null,"repeat");if(0>a||1342177279<a)throw new window.RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=b),a>>>=1)b+=b;return d}});ja("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=ka(this,a,"startsWith");a+="";for(var e=b.length,f=a.length,h=Math.max(0,Math.min(c|0,b.length)),k=0;k<f&&h<e;)if(b[h++]!=a[k++])return!1;return k>=f}});_.la=_.la||{};_.r=this;
_.na=function(a){return void 0!==a};
_.pa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.qa=function(a){return"array"==_.pa(a)};_.t=function(a){return"string"==typeof a};_.ta="closure_uid_"+(1E9*Math.random()>>>0);ya=function(a,b,c){return a.call.apply(a.bind,arguments)};
za=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.u=function(a,b,c){_.u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ya:za;return _.u.apply(null,arguments)};
_.Aa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.Ca=Date.now||function(){return+new Date};_.A=function(a,b){var c=a.split("."),d=_.r;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.na(b)?d[e]=b:d=d[e]?d[e]:d[e]={}};
_.C=function(a,b){function c(){}c.prototype=b.prototype;a.S=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.jL=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.Da=function(a,b){return b};_.D=function(a,b){b=_.Da(a,b);_.A(a,b)};_.Ea=window.gadgets||{};_.Ga=window.osapi=window.osapi||{};_.google=window.google||{};window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{rms:"migrated"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},udc_webconsentflow:{url:"https://myaccount.google.com/webconsent?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},
requestCache:{enabled:!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:!0},transport:{isProxyShared:!0},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});
_.Ia=window;_.Ja=window.document;_.Na=_.Ia.location;_.Oa=/\[native code\]/;_.Pa=function(a,b,c){return a[b]=a[b]||c};_.Ra=function(){var a;if((a=Object.create)&&_.Oa.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.Sa=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.Ta=function(a,b){if(!a)throw Error(b||"");};_.Va=_.Pa(_.Ia,"gapi",{});
_.Wa=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.Ya=function(a,b,c){_.Xa(a,b,c,"add","at")};_.Xa=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.Za=_.Pa(_.Ia,"___jsl",_.Ra());_.Pa(_.Za,"I",0);_.Pa(_.Za,"hel",10);var $a,ab,cb,db,eb,gb;$a=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};ab=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};cb=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};db=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]&&b[c]&&"object"===typeof a[c]&&"object"===typeof b[c]&&!cb(a[c])&&!cb(b[c])?db(a[c],b[c]):b[c]&&"object"===typeof b[c]?(a[c]=cb(b[c])?[]:{},db(a[c],b[c])):a[c]=b[c])};
eb=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var b;try{b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
gb=function(a){ab(!0);var b=window.___gcfg,c=$a("cu");if(b&&b!==window.___gu){var d={};db(d,b);c.push(d);window.___gu=b}var b=$a("cu"),e=window.document.scripts||window.document.getElementsByTagName("script")||[],d=[],f=[];f.push.apply(f,$a("us"));for(var h=0;h<e.length;++h)for(var k=e[h],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",
!0),(f=d[e])?(h=f.nodeType,f=3==h||4==h?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=eb(f))&&b.push(f));a&&(d={},db(d,a),c.push(d));d=$a("cd");a=0;for(b=d.length;a<b;++a)db(ab(),d[a]);d=$a("ci");a=0;for(b=d.length;a<b;++a)db(ab(),d[a]);a=0;for(b=c.length;a<b;++a)db(ab(),c[a])};_.E=function(a,b){if(!a)return ab();for(var c=a.split("/"),d=ab(),e=0,f=c.length;d&&"object"===typeof d&&e<f;++e)d=d[c[e]];return e===c.length&&void 0!==d?d:b}; _.hb=function(a,b){var c=a;if("string"===typeof a){for(var d=c={},e=a.split("/"),f=0,h=e.length;f<h-1;++f)var k={},d=d[e[f]]=k;d[e[f]]=b}gb(c)};
var ib=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.Pa(_.Za,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};ib&&ib();gb();_.D("gapi.config.get",_.E);_.D("gapi.config.update",_.hb);
var qb,rb,wb,xb,yb,Ab,Bb,Cb,Db,Eb,Fb,Hb,Jb,Lb,Nb;_.lb=function(a){return!!a&&"object"===typeof a&&_.Oa.test(a.push)};_.mb=function(a,b,c){if(a){_.Ta(_.lb(a),"arrayForEach was called with a non array value");for(var d=0;d<a.length;d++)b.call(c,a[d],d)}};_.nb=function(a,b,c){if(a)if(_.lb(a))_.mb(a,b,c);else{_.Ta("object"===typeof a,"objectForEach was called with a non object value");c=c||a;for(var d in a)_.Sa(a,d)&&void 0!==a[d]&&b.call(c,a[d],d)}};
qb=function(a){a=a.sort();for(var b=[],c=void 0,d=0;d<a.length;d++){var e=a[d];e!=c&&b.push(e);c=e}return b};rb=function(){var a=[],b=_.Za.H;b&&_.nb(b,function(b){a.push.apply(a,b.L)});return qb(a)};_.sb=function(a){if(_.Oa.test(Object.keys))return Object.keys(a);var b=[],c;for(c in a)_.Sa(a,c)&&b.push(c);return b};Cb={};Db=0;Eb=_.Ra();Fb=_.Ra();Hb=function(a){return"number"===typeof a&&a>Math.random()};
_.Ib=function(a){if("undefined"===typeof wb){var b=_.E("report")||{},c=b.rate;Ab=b.timeout||1E3;xb=b.host||"https://plus.google.com";yb=b.path||"/_/widget/report";wb=[];Hb(c)&&(wb=b.apis||[]);var b=b.apiRate||{},d;for(d in b)Hb(b[d])&&wb.push(d)}for(d=0;d<wb.length;++d)if((new RegExp("^"+wb[d]+"$")).test(a))return!0;return!1};Jb=function(a){delete Cb[a]};
Lb=function(){Bb&&(_.Ia.clearTimeout(Bb),Bb=0);Bb=_.Ia.setTimeout(function(){var a;a=window.document.location;a=a.protocol+"//"+a.host+a.pathname;var b=_.sb(Fb).join(":");a=[xb,yb,"?api=",(0,window.encodeURIComponent)(b),"&url=",(0,window.encodeURIComponent)(a),"&loaded=",(0,window.encodeURIComponent)(rb().join(":"))].join("");Fb=_.Ra();var b=new window.Image,c=Db++;Cb[c]=b;b.onload=b.onerror=_.Aa(Jb,c);b.src=a;Bb=0},Ab)};_.Mb=function(a){Eb[a]||(Fb[a]=!0,Eb[a]=!0,Lb())};Nb=_.Da; _.Da=function(a,b){var c=Nb(a,b);"function"===typeof b&&_.Ib(a)&&(c=function(c){_.Mb(a);return b.apply(this,arguments)});return c};

_.uj=window.googleapis&&window.googleapis.server||{};
_.lk=function(){var a=/\s*;\s*/;return{get:function(b,c){for(var d=b+"=",e=(window.document.cookie||"").split(a),f=0,h;h=e[f];++f)if(0==h.indexOf(d))return h.substr(d.length);return c}}}();
_.Rb=function(){function a(a,b){if(!(a<c)&&d)if(2===a&&d.warn)d.warn(b);else if(3===a&&d.error)try{d.error(b)}catch(h){}else d.log&&d.log(b)}var b=function(b){a(1,b)};_.Pb=function(b){a(2,b)};_.Ob=function(b){a(3,b)};_.Qb=function(){};b.INFO=1;b.WARNING=2;b.NONE=4;var c=1,d=window.console?window.console:window.opera?window.opera.postError:void 0;return b}();

_.F=_.F||{};
_.F=_.F||{};(function(){var a=[];_.F.Ria=function(b){a.push(b)};_.F.fja=function(){for(var b=0,c=a.length;b<c;++b)a[b]()}})();
_.Sb=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1};_.Ub=function(a,b){var c=_.Pa(_.Za,"watt",_.Ra());_.Pa(c,a,b)};_.F=_.F||{};
(function(){var a=null;_.F.Xc=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");for(var e=window.decodeURIComponent?window.decodeURIComponent:window.unescape,f=0,h=b.length;f<h;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k),k=b[f].substring(k+1),k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(m){}}}c&&(a=d);return d}; _.F.Xc()})();
_.D("gadgets.util.getUrlParameters",_.F.Xc);
_.Vb=window.console;_.Yb=function(a){_.Vb&&_.Vb.log&&_.Vb.log(a)};_.Zb=function(){};
_.$b=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&_.hb(a());return{register:function(a,c,d){d&&d(_.E())},get:function(a){return _.E(a)},update:function(a,c){if(c)throw"Config replacement is not supported";_.hb(a)},Pc:function(){}}}();
_.D("gadgets.config.register",_.$b.register);_.D("gadgets.config.get",_.$b.get);_.D("gadgets.config.init",_.$b.Pc);_.D("gadgets.config.update",_.$b.update);
var ac=function(a){return 10>a?"0"+a:a},bc={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},cc=function(a){var b,c,d;b=/[\"\\\x00-\x1f\x7f-\x9f]/g;if(void 0!==a){switch(typeof a){case "string":return b.test(a)?'"'+a.replace(b,function(a){var b=bc[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";
b=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){d=a.length;for(c=0;c<d;c+=1)b.push(cc(a[c])||"null");return"["+b.join(",")+"]"}for(c in a)!/___$/.test(c)&&_.Sa(a,c)&&"string"===typeof c&&(d=cc(a[c]))&&b.push(cc(c)+":"+d);return"{"+b.join(",")+"}"}return""}},dc=function(a){if(!a)return!1;if(/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))try{return eval("("+
a+")")}catch(b){}return!1},ec=!1,fc;try{ec=!!window.JSON&&'["a"]'===window.JSON.stringify(["a"])&&"a"===window.JSON.parse('["a"]')[0]}catch(a){}fc=function(a){try{return window.JSON.parse(a)}catch(b){return!1}};_.gc=ec?window.JSON.stringify:cc;_.hc=ec?fc:dc;fc||(Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",ac(this.getUTCMonth()+1),"-",ac(this.getUTCDate()),"T",ac(this.getUTCHours()),":",ac(this.getUTCMinutes()),":",ac(this.getUTCSeconds()),"Z"].join("")});

_.D("gadgets.json.stringify",_.gc);_.D("gadgets.json.parse",_.hc);_.Wa(_.Ia.location.href,"rpctoken")&&_.Ya(_.Ja,"unload",function(){});
var kc;_.ic=function(){var a=_.Ja.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.jc=function(a){if(_.ic())a();else{var b=!1,c=function(){if(!b)return b=!0,a.apply(this,arguments)};_.Ia.addEventListener?(_.Ia.addEventListener("load",c,!1),_.Ia.addEventListener("DOMContentLoaded",c,!1)):_.Ia.attachEvent&&(_.Ia.attachEvent("onreadystatechange",function(){_.ic()&&c.apply(this,arguments)}),_.Ia.attachEvent("onload",c))}};kc=kc||{};kc.tR=null; kc.RP=null;kc.Uy=null;kc.frameElement=null;
kc=kc||{};
kc.qJ||(kc.qJ=function(){function a(a){"undefined"!=typeof window.addEventListener?window.addEventListener("message",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onmessage",a);window.___jsl=window.___jsl||{};var b=window.___jsl;b.RPMQ=b.RPMQ||[];b.RPMQ.push(a)}function b(a){var b=(0,_.hc)(a.data);if(b&&b.f){(0,_.Qb)("gadgets.rpc.receive("+window.name+"): "+a.data);var d=_.G.zl(b.f);e&&("undefined"!==typeof a.origin?a.origin!==d:a.domain!==/^.+:\/\/([^:]+).*/.exec(d)[1])?_.Ob("Invalid rpc message origin. "+
d+" vs "+(a.origin||"")):c(b,a.origin)}}var c,d,e=!0;return{Gp:function(){return"wpm"},t3:function(){return!0},Pc:function(f,h){_.$b.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(e=!1)});c=f;d=h;a(b);d("..",!0);return!0},yd:function(a){d(a,!0);return!0},call:function(a,b,c){var d=_.G.zl(a),e=_.G.KK(a);d?window.setTimeout(function(){var a=(0,_.gc)(c);(0,_.Qb)("gadgets.rpc.send("+window.name+"): "+a);e.postMessage(a,d)},0):".."!=a&&_.Ob("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
kc=kc||{};
kc.by||(kc.by=function(){function a(a,b){K[b]=K[b]||function(){a.apply({},arguments)}}function b(){if(null===v&&window.document.body&&l){var a=l+"?cb="+Math.random()+"&origin="+B+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="___xpcswf" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;v=c.firstChild}++z;null!==w&&(null!==v||50<=z)?window.clearTimeout(w):w=window.setTimeout(b,100)}function c(){N[".."]||(k(".."),y++,50<=y&&null!==J?(window.clearTimeout(J),J=null):J=window.setTimeout(c,100))}function d(){if(null!==v&&v.setup)for(;0<x.length;){var a=x.shift(),b=a.w8;v.setup(a.Dr,".."===b?_.G.LB:b,".."===b?"INNER":"OUTER")}null!==w&&window.clearTimeout(w);w=null}function e(){N[".."]||null!==
J||(J=window.setTimeout(c,100))}function f(a,b,c){b=_.G.zl(a);var d=_.G.ql(a);v["sendMessage_"+(".."===a?_.G.LB:a)+"_"+d+"_"+(".."===a?"INNER":"OUTER")].call(v,(0,_.gc)(c),b);return!0}function h(a,b){var c=(0,_.hc)(a),d=c._scr;d?(p(d,!0),N[d]=!0,".."!==d&&k(d,!0)):window.setTimeout(function(){n(c,b)},0)}function k(a,b){var c=_.G.LB,d={};d._scr=b?"..":c;d._pnt=c;f(a,0,d)}var l=null,m=!1,n=null,p=null,v=null,x=[],w=null,z=0,y=0,J=null,N={},B=window.location.protocol+"//"+window.location.host,K;window.___jsl=
window.___jsl||{};K=window.___jsl._fm={};_.$b.register("rpc",null,function(a){m&&(l=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(d,"ready");a(e,"setupDone");a(h,"receiveMessage");return{Gp:function(){return"flash"},t3:function(){return!0},Pc:function(a,b){n=a;p=b;return m=!0},yd:function(a,c){x.push({Dr:c,w8:a});null===v&&null===w&&(w=window.setTimeout(b,100));return!0},call:f,kX:h,Yga:d,Zga:e}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.G&&_.G||(_.G=window.gadgets.rpc,_.G.config=_.G.config,_.G.register=_.G.register,_.G.unregister=_.G.unregister,_.G.$Q=_.G.registerDefault,_.G.uT=_.G.unregisterDefault,_.G.QM=_.G.forceParentVerifiable,_.G.call=_.G.call,_.G.Vt=_.G.getRelayUrl,_.G.rj=_.G.setRelayUrl,_.G.EA=_.G.setAuthToken,_.G.Mv=_.G.setupReceiver,_.G.ql=_.G.getAuthToken,_.G.gH=_.G.removeReceiver,_.G.uN=_.G.getRelayChannel,_.G.lA=_.G.receive,_.G.WQ=_.G.receiveSameDomain,_.G.qb=
_.G.getOrigin,_.G.zl=_.G.getTargetOrigin,_.G.KK=_.G._getTargetWin,_.G.jX=_.G._parseSiblingId);else{_.G=function(){function a(a,b){if(!oa[a]){var c=aa;b||(c=Ka);oa[a]=c;for(var d=ra[a]||[],e=0;e<d.length;++e){var f=d[e];f.t=N[a];c.call(a,f.f,f)}ra[a]=[]}}function b(){function a(){da=!0}Y||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),Y=!0)}function c(a,c,d,e,f){N[c]&&N[c]===d||(_.Ob("Invalid gadgets.rpc token. "+
N[c]+" vs "+d),Ha(c,2));f.onunload=function(){M[c]&&!da&&(Ha(c,1),_.G.gH(c))};b();e=(0,_.hc)((0,window.decodeURIComponent)(e))}function d(b,c){if(b&&"string"===typeof b.s&&"string"===typeof b.f&&b.a instanceof Array)if(N[b.f]&&N[b.f]!==b.t&&(_.Ob("Invalid gadgets.rpc token. "+N[b.f]+" vs "+b.t),Ha(b.f,2)),"__ack"===b.s)window.setTimeout(function(){a(b.f,!0)},0);else{b.c&&(b.callback=function(a){_.G.call(b.f,(b.g?"legacy__":"")+"__cb",null,b.c,a)});if(c){var d=e(c);b.origin=c;var f=b.r,h;try{h=e(f)}catch(ha){}f&&
h==d||(f=c);b.referer=f}d=(z[b.s]||z[""]).apply(b,b.a);b.c&&"undefined"!==typeof d&&_.G.call(b.f,"__cb",null,b.c,d)}}function e(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a)throw Error("b");
var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c}function f(a){if("/"==a.charAt(0)){var b=a.indexOf("|");return{id:0<b?a.substring(1,b):a.substring(1),origin:0<b?a.substring(b+1):null}}return null}function h(a){if("undefined"===typeof a||".."===a)return window.parent;var b=f(a);if(b)return window.top.frames[b.id];a=String(a);return(b=window.frames[a])?b:(b=window.document.getElementById(a))&&b.contentWindow?
b.contentWindow:null}function k(a,b){if(!0!==M[a]){"undefined"===typeof M[a]&&(M[a]=0);var c=h(a);".."!==a&&null==c||!0!==aa.yd(a,b)?!0!==M[a]&&10>M[a]++?window.setTimeout(function(){k(a,b)},500):(oa[a]=Ka,M[a]=!0):M[a]=!0}}function l(a){(a=y[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function m(a,b,c){b&&!/http(s)?:\/\/.+/.test(b)&&(0==b.indexOf("//")?b=window.location.protocol+
b:"/"==b.charAt(0)?b=window.location.protocol+"//"+window.location.host+b:-1==b.indexOf("://")&&(b=window.location.protocol+"//"+b));y[a]=b;"undefined"!==typeof c&&(J[a]=!!c)}function n(a,b){b=b||"";N[a]=String(b);k(a,b)}function p(a){a=(a.passReferrer||"").split(":",2);Ma=a[0]||"none";ea=a[1]||"origin"}function v(b){"true"===String(b.useLegacyProtocol)&&(aa=kc.Uy||Ka,aa.Pc(d,a))}function x(a,b){function c(c){c=c&&c.rpc||{};p(c);var d=c.parentRelayUrl||"",d=e(X.parent||b)+d;m("..",d,"true"===String(c.useLegacyProtocol));
v(c);n("..",a)}!X.parent&&b?c({}):_.$b.register("rpc",null,c)}function w(a,b,c){if(".."===a)x(c||X.rpctoken||X.ifpctok||"",b);else a:{var d=null;if("/"!=a.charAt(0)){if(!_.F)break a;d=window.document.getElementById(a);if(!d)throw Error("c`"+a);}d=d&&d.src;b=b||_.G.qb(d);m(a,b);b=_.F.Xc(d);n(a,c||b.rpctoken)}}var z={},y={},J={},N={},B=0,K={},M={},X={},oa={},ra={},Ma=null,ea=null,Z=window.top!==window.self,xa=window.name,Ha=function(){},sa=window.console,Fa=sa&&sa.log&&function(a){sa.log(a)}||function(){},
Ka=function(){function a(a){return function(){Fa(a+": call ignored")}}return{getCode:function(){return"noop"},isParentVerifiable:function(){return!0},init:a("init"),setup:a("setup"),call:a("call")}}();_.F&&(X=_.F.Xc());var da=!1,Y=!1,aa=function(){if("flash"==X.rpctx)return kc.by;if("rmr"==X.rpctx)return kc.tR;var a="function"===typeof window.postMessage?kc.qJ:"object"===typeof window.postMessage?kc.qJ:window.ActiveXObject?kc.by?kc.by:kc.RP?kc.RP:kc.Uy:0<window.navigator.userAgent.indexOf("WebKit")?
kc.tR:"Gecko"===window.navigator.product?kc.frameElement:kc.Uy;a||(a=Ka);return a}();z[""]=function(){Fa("Unknown RPC service: "+this.s)};z.__cb=function(a,b){var c=K[a];c&&(delete K[a],c.call(this,b))};return{config:function(a){"function"===typeof a.CR&&(Ha=a.CR)},register:function(a,b){if("__cb"===a||"__ack"===a)throw Error("d");if(""===a)throw Error("e");z[a]=b},unregister:function(a){if("__cb"===a||"__ack"===a)throw Error("f");if(""===a)throw Error("g");delete z[a]},$Q:function(a){z[""]=a},uT:function(){delete z[""]},
QM:function(){},call:function(a,b,c,d){a=a||"..";var e="..";".."===a?e=xa:"/"==a.charAt(0)&&(e=_.G.qb(window.location.href),e="/"+xa+(e?"|"+e:""));++B;c&&(K[B]=c);var h={s:b,f:e,c:c?B:0,a:Array.prototype.slice.call(arguments,3),t:N[a],l:!!J[a]},k;a:if("bidir"===Ma||"c2p"===Ma&&".."===a||"p2c"===Ma&&".."!==a){k=window.location.href;var l="?";if("query"===ea)l="#";else if("hash"===ea)break a;l=k.lastIndexOf(l);l=-1===l?k.length:l;k=k.substring(0,l)}else k=null;k&&(h.r=k);if(".."===a||null!=f(a)||window.document.getElementById(a))(k=
oa[a])||null===f(a)||(k=aa),0===b.indexOf("legacy__")&&(k=aa,h.s=b.substring(8),h.c=h.c?h.c:B),h.g=!0,h.r=e,k?(J[a]&&(k=kc.Uy),!1===k.call(a,e,h)&&(oa[a]=Ka,aa.call(a,e,h))):ra[a]?ra[a].push(h):ra[a]=[h]},Vt:l,rj:m,EA:n,Mv:w,ql:function(a){return N[a]},gH:function(a){delete y[a];delete J[a];delete N[a];delete M[a];delete oa[a]},uN:function(){return aa.Gp()},lA:function(a,b){4<a.length?aa.kX(a,d):c.apply(null,a.concat(b))},WQ:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){d(a)},
0)},qb:e,zl:function(a){var b=l(a);a=b?b:(b=f(a))?b.origin:".."==a?X.parent:window.document.getElementById(a).src;return e(a)},Pc:function(){!1===aa.Pc(d,a)&&(aa=Ka);Z?w(".."):_.$b.register("rpc",null,function(a){a=a.rpc||{};p(a);v(a)})},KK:h,jX:f,o9:"__ack",LB:xa||"..",Vea:0,Uea:1,Tea:2}}();_.G.Pc()};
_.G.config({CR:function(a){throw Error("h`"+a);}});_.Qb=_.Zb;_.D("gadgets.rpc.config",_.G.config);_.D("gadgets.rpc.register",_.G.register);_.D("gadgets.rpc.unregister",_.G.unregister);_.D("gadgets.rpc.registerDefault",_.G.$Q);_.D("gadgets.rpc.unregisterDefault",_.G.uT);_.D("gadgets.rpc.forceParentVerifiable",_.G.QM);_.D("gadgets.rpc.call",_.G.call);_.D("gadgets.rpc.getRelayUrl",_.G.Vt);_.D("gadgets.rpc.setRelayUrl",_.G.rj);_.D("gadgets.rpc.setAuthToken",_.G.EA);_.D("gadgets.rpc.setupReceiver",_.G.Mv);_.D("gadgets.rpc.getAuthToken",_.G.ql); _.D("gadgets.rpc.removeReceiver",_.G.gH);_.D("gadgets.rpc.getRelayChannel",_.G.uN);_.D("gadgets.rpc.receive",_.G.lA);_.D("gadgets.rpc.receiveSameDomain",_.G.WQ);_.D("gadgets.rpc.getOrigin",_.G.qb);_.D("gadgets.rpc.getTargetOrigin",_.G.zl);

_.H={};_.Uc={};window.iframer=_.Uc;
_.Vc=function(a){var b=_.pa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.Wc=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.Xc=function(a){return"number"==typeof a};_.Yc=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.Zc=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.$c=2147483648*Math.random()|0;
_.Nh=function(a){return(0,window.encodeURIComponent)(String(a))};_.Oh=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;_.Ph=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};_.Qh=function(a,b,c){if(_.qa(b))for(var d=0;d<b.length;d++)_.Qh(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",_.Nh(b))}; _.Rh=function(a,b){for(var c in b)_.Qh(c,b[c],a);return a};

var Mk;_.Kk=function(a){if(!_.Vc(a))return null;for(var b={},c=0;c<a.length;c++)b[a[c]]=a[c];return b};_.Lk=function(a,b){var c=a.length;if(c!=b.length)return!1;for(var d=0;d<c;++d){var e=a.charCodeAt(d),f=b.charCodeAt(d);65<=e&&90>=e&&(e+=32);65<=f&&90>=f&&(f+=32);if(e!=f)return!1}return!0};Mk=null;
_.Nk=function(a){if(null===Mk){var b=_.E("client/headers/response");b||(b=_.E("googleapis/headers/response"));Mk=_.Kk(b)}if(null!=Mk){if(Mk.hasOwnProperty(a))return!0;for(var c in Mk)if(Mk.hasOwnProperty(c)&&_.Lk(c,a))return!0}return!1};
_.Ok=function(a){a=String(a||"").split("\x00").join("");for(var b=[],c=!0,d=0,e=a.length;d<e;++d){var f=a.charAt(d),h=a.charCodeAt(d);if(55296<=h&&56319>=h&&d+1<e){var k=a.charAt(d+1),l=a.charCodeAt(d+1);56320<=l&&57343>=l&&(f+=k,h=65536+(h-55296<<10)+(l-56320),++d)}if(!(0<=h&&1114109>=h)||55296<=h&&57343>=h||64976<=h&&65007>=h||65534==(h&65534))h=65533,f=String.fromCharCode(h);k=!(32<=h&&126>=h)||" "==f||c&&":"==f||"\\"==f;!c||"/"!=f&&"?"!=f||(c=!1);"%"==f&&(d+2>=e?k=!0:(l=16*(0,window.parseInt)(a.charAt(d+
1),16)+(0,window.parseInt)(a.charAt(d+2),16),0<=l&&255>=l?(h=l,f=0==h?"":"%"+(256+l).toString(16).toUpperCase().substr(1),d+=2):k=!0));k&&(f=(0,window.encodeURIComponent)(f),1>=f.length&&(0<=h&&127>=h?f="%"+(256+h).toString(16).toUpperCase().substr(1):(h=65533,f=(0,window.encodeURIComponent)(String.fromCharCode(h)))));b.push(f)}a=b.join("");a=a.split("#")[0];a=a.split("?");b=a[0].split("/");c=[];d=0;for(e=b.length;d<e;++d)f=b[d],h=f.split("%2E").join("."),h=h.split((0,window.encodeURIComponent)("\uff0e")).join("."),
"."==h?d+1==e&&c.push(""):".."==h?(0<c.length&&c.pop(),d+1==e&&c.push("")):c.push(f);a[0]=c.join("/");for(a=a.join("?");a&&"/"==a.charAt(0);)a=a.substr(1);return"/"+a};_.Qk=function(a){var b=_.Ok(a);if(String(a)!=b)throw Error("G");(a=b)&&"/"==a.charAt(a.length-1)||(a=(a||"")+"/");_.G.register("init",function(){_.Qk(a)});_.Pk=a;_.F.Xc(window.location.href)};
_.Rk="function"==typeof window.atob;
var Sk,Tk,Uk,Vk,Wk,Xk,Yk,Zk,$k;Sk=null;Tk=function(a,b){if(null!=a)for(var c in a)if(a.hasOwnProperty(c)&&_.Lk(c,b))return{name:c,value:a[c]}};Uk=null;
Vk=function(a,b,c,d){var e=Tk(b,"X-Goog-Safety-Encoding");if(null!=e){if(_.Rk)a=window.atob(a);else{if(!Sk){var f="ABCDEFGHIJKLMNOPQRSTUVWXYZ",f=f+(f.toLowerCase()+"0123456789+/=");Sk={};for(var h=0;h<f.length;h++)Sk[f.charAt(h)]=h}for(var f=Sk,h=[],k=0;k<a.length;){var l=f[a.charAt(k++)],m=k<a.length?f[a.charAt(k)]:0;++k;var n=k<a.length?f[a.charAt(k)]:0;++k;var p=k<a.length?f[a.charAt(k)]:0;++k;if(null==l||null==m||null==n||null==p)throw Error();h.push(l<<2|m>>4);64!=n&&(h.push(m<<4&240|n>>2),64!=
p&&h.push(n<<6&192|p))}a=String.fromCharCode.apply(null,h)}f=Tk(b,"X-Goog-Safety-Content-Type");b["Content-Type"]=f.value;delete b[e.name];delete b[f.name]}return{body:a,headers:b,status:c,statusText:d}};Wk=function(){try{return new window.XMLHttpRequest}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(a){}return null};Xk=function(a,b){b=b||"0.1";var c=[];c.push(a||"google-api-javascript-client");b&&(c.push("/"),c.push(b));return c.join("")};
Yk=function(a,b){if(!a||!b)return!1;for(var c=0,d=b.length;c<d;++c){var e=b.charCodeAt(c);if(!(32<=e&&126>=e))return!1}null===Uk&&((c=_.E("client/headers/request"))||(c=_.E("googleapis/headers/request")),Uk=_.Kk(c));return null!=Uk?Uk.hasOwnProperty(a):!1};
Zk=function(a,b,c,d){a=a||{};var e=a.headers||{},f=a.httpMethod||"GET",h=String(a.url||""),k=a.urlParams||null,l=a.body||null,m=a.clientName||null,n=a.clientVersion||null;c=c||null;d=d||null;h=_.Ok(h);h=_.Pk+String(h||"/").substr(1);h=_.Ph(_.Rh([h],k));e["X-JavaScript-User-Agent"]=Xk(m,n);delete e["X-Origin"];c&&(e["X-Origin"]=c);delete e["X-Referer"];d&&(e["X-Referer"]=d);e["X-Goog-Encode-Response-If-Executable"]="base64";l&&"object"===typeof l&&(l=(0,_.gc)(l));var p=Wk();if(!p)throw Error("H");
p.open(f,h);p.onreadystatechange=function(){if(4==p.readyState&&0!==p.status){var a=p.responseText;var c=p.getAllResponseHeaders(),d={};if(c)for(var c=c.split("\r\n"),e=0;e<c.length;e++){var f=c[e],h=f.indexOf(": ");if(0<h){var k=f.substring(0,h),f=f.substring(h+2);_.Nk(k)&&(d[k]=f)}}a=Vk(a,d,p.status,p.statusText);b(a)}};p.onerror=function(){var c;c={error:{code:-1,message:"A network error occurred, and the request could not be completed."}};if("/rpc"==a.url){for(var d=a.body,e=[],f=0;f<d.length;f++){var h=
(0,_.gc)(c),h=(0,_.hc)(h);h.id=d[f].id;e.push(h)}c=e}c=(0,_.gc)(c);c=Vk(c);b(c)};for(var v in e)e.hasOwnProperty(v)&&(f=e[v],Yk(v,f)&&p.setRequestHeader(v,f));p.send(l?l:null)};$k=function(a,b,c,d){var e={},f=0;if(0==a.length)b(e);else{var h=function(k){var l=k.key;Zk(k.params,function(c){e[l]={data:c};f++;a.length==f?b((0,_.gc)(e)):h(a[f])},c,d)};h(a[f])}};_.uj=_.uj||{};
_.uj.Y5=function(){_.G.register("makeHttpRequests",function(a){".."==this.f&&this.t==_.G.ql("..")&&this.origin==_.G.zl("..")&&$k.call(this,a,this.callback,this.origin,this.referer)})};_.uj.Pc=function(){var a=String(window.location.pathname);18<=a.length&&"/static/proxy.html"==a.substr(a.length-18)&&(a=a.substr(0,a.length-18));a||(a="/");_.uj.KO(a)};_.uj.KO=function(a){var b=_.Ok(a);if(String(a)!=b)throw Error("G");_.uj.Y5();_.Qk(a);_.G.call("..","ready:"+_.G.ql(".."))};
_.D("googleapis.ApiServer.makeHttpRequests",$k);_.D("googleapis.ApiServer.initWithPath",_.Qk);_.D("googleapis.server.init",_.uj.Pc);_.D("googleapis.server.initWithPath",_.uj.KO);
});
// Google Inc.
